language: node_js
node_js:
  - "12.0.0"

branches:
  only:
    - develop
cache:
  directories:
    - node_modules

before_script:
  - npm install -g @angular/cli

script:
  - npm run build

after_success:
  - npm run after-deploy

notifications:
  email:
    on_failure: change
    on_success: change

deploy:
  provider: pages
  skip-cleanup: true
  local_dir: dist
  github-token: $GITHUB_TOKEN
  keep-history: false
  on:
    branch: develop
  target-branch: master
